### ISSUE TITLE
Presence feed not defined in POD spec 1.48

### ISSUE THREAD

**Issue by ftbb** [symphonyoss/symphony-api-spec#10]
Not seeing https://rest-api.symphony.com/docs/read-presence-feed defined in spec.

**Comment by dnsymphony** [comment]
Presence feed is limited release in 1.48.  If it works for beta customers it will be made available in the released YAML files.

**Comment by dnsymphony** [comment]
Presence feed IS supposed to be in 1.48. 1.48.1 version of the spec will be released soon and will add these missing endpoints.
