### ISSUE TITLE
Swagger Definitions

### ISSUE THREAD

**Issue by robmoffat** [symphonyoss/symphony-api-spec#41]
I've just raised [this](https://support.symphony.com/hc/en-us/requests/19913) with Symphony support, but maybe this is this is the right place?

The V4Event specification published here: https://github.com/symphonyoss/symphony-api-spec/blob/master/agent/agent-api-public.yaml#L3821

Doesn't contain the `SYMPHONYELEMENTSACTION` field, and doesn't contain the object definitions to describe this payload:

```
"symphonyElementsAction": {
"actionStream": {
"streamId": "0YeiA-neZa1PrdHy1L82jX___pQjntU-dA"
},
"formStream": {
"streamId": "YuK1c2y2yuie6+UfQnjSPX///pQEn69idA=="
},
"formMessageId": "xtZqqBNGwLDkLuvuQTyjH3///pQENvjudA==5454",
"formId": "form_id",
"formValues": {
"action": "submit_button",
"name_01": "John",
"email_01": "john@email.com",
"country": "opt1",
"example_radio": "option_01",
"checkbox_1": "value01",
"checkbox_2": "value02",
"comment": "my comment"
}
}
```

Can someone take a look at the swagger definitions and update them please?

**Comment by robmoffat** [comment]
Tried creating PR https://github.com/symphonyoss/symphony-api-spec/pull/42 for this but CCLA nonsense

**Comment by cristiadu** [comment]
We have #43 updating all APIs instead.
