### ISSUE TITLE
Agent Deprecated API Yaml doesn't contain all the definitions found in public

### ISSUE THREAD

**Issue by robmoffat** [symphonyoss/symphony-api-spec#69]
For all other apis, the -public-deprecated.yml file is strictly a superset of the contents of the -public.yml file.  However, this rule has recently been broken in the agent file.

**Comment by robmoffat** [comment]
This is addressed by the following PR https://github.com/symphonyoss/symphony-api-spec/pull/70

**Comment by symphony-youri** [comment]
Closing it as the linked PR as been merged.
