### ISSUE TITLE
Unable to swagger-gen rc48 spec due to String model overloading 

### ISSUE THREAD

**Issue by ftbb** [symphonyoss/symphony-api-spec#8]
Using the deprecated rc48 POD spec and Swagger v1.5.16

Swagger generation returns errors on String model being overridden within the spec itself.

[ERROR] ..../symphony-java-api/pod/target/generated-sources/swagger/src/main/java/org/symphonyoss/symphony/pod/model/CompanyCertInfo.java:[200,17] toString() in org.symphonyoss.symphony.pod.model.CompanyCertInfo cannot override toString() in java.lang.Object
  return type org.symphonyoss.symphony.pod.model.String is not compatible with java.lang.String

In spec:

String:
      type: string

**Comment by dnsymphony** [comment]
That doesn't cause any errors for me.

When exactly do you get that error?

**Comment by ftbb** [comment]
We are using swagger 1.5.6 and cogen 2.2.2 as part of project symphony-java-api. 

Yes, codegen is generating org.symphonyoss.symphony.pod.model.String, which is core to this issue.
