### ISSUE TITLE
Feature Request:  Schemas

### ISSUE THREAD

**Issue by robmoffat** [symphonyoss/symphony-api-spec#86]
Hi,

Can someone produce a Schema for checking MessageML/PresentationML?  It appears that there is a lot of checking going on in the agent code, so perhaps this exists already and can be surfaced. 

Reason being, it would allow client-side checking of messages before getting them refused from the agent. 

thanks,
Rob

**Comment by dnsymphony** [comment]
You can use https://github.com/symphonyoss/messageml-utils.  It's not a schema, though.  It's a Java library that can be used to parse MessageML.

**Comment by robmoffat** [comment]
I am aware of that library.  Is this what the agent also uses?
thanks,
Rob

**Comment by dnsymphony** [comment]
Yep

**Comment by symphony-youri** [comment]
I wish we had a spec for messageML too :), but for now we'll probably to stick with https://github.com/symphonyoss/messageml-utils
